#!/usr/bin/env bash
########
set -x
set -e

export LC_ALL=C

source /common.sh



# ADD OUR NEW DEFAULT USER ------------------------------------------------------------------------------------------------------------------------------------
adduser --gecos "" --disabled-password $LAB_BOX_USER
chpasswd <<<"$LAB_BOX_USER:$LAB_BOX_USER_PASSWORD"
usermod -a -G users,adm,dialout,tty,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo $LAB_BOX_USER
# Show a control output which groups the user is in
groups $RASPI_USER

# Make sure user doesn't require a password when running as sudo; https://github.com/Pioreactor/CustoPiZer/blob/pioreactor/workspace/scripts/01-make-pioreactor-user.sh
echo "$RASPI_USER ALL=(ALL) NOPASSWD: ALL" | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/010_$RASPI_USER-nopasswd

# Remove SSH pre-authentication banner
if [ -fe /etc/ssh/sshd_config.d/rename_user.conf ]
then 
  rm -f /etc/ssh/sshd_config.d/rename_user.conf
fi


# UPDATE SOFTWARE  --------------------------------------------------------------------------------------------------------------------------------------------
apt-get update
apt-get -y full-upgrade
apt-get -y --allow-change-held-packages install python3 python3-virtualenv python3-dev git
echo "Reinstall iputils-ping"
apt-get -y --force-yes install --reinstall iputils-ping
# TODO: remove unneeded software?
apt-get autoremove -y


# SETUP RTC ---------------------------------------------------------------------------------------------------------------------------------------------------
# Done like here: https://tutorials-raspberrypi.de/raspberry-pi-rtc-modul-i2c-echtzeituhr/ but there are many tutorials out there
apt-get install -y i2c-tools
echo -e "i2c-dev\nrtc-ds1307" >> /etc/modules
sed -i -e '$i echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device\nhwclock --hctosys\n\n' /etc/rc.local
cat /etc/rc.local










### Script ####

# unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
# unpack /filesystem/home/root /root root
# unpack /filesystem/boot /boot/firmware




if [ "${LAB_BOX_PYTHON_GUI_INSTALL}" == "yes" ]
then
  echo "Installing Lab-Box Python GUI from repo ${LAB_BOX_PYTHON_GUI_REPO}"
  mkdir /home/"${BASE_USER}"/lab-box-python-gui
  cd /home/"${BASE_USER}"/lab-box-python-gui

  # Clone the Lab-Box-Python-GUI repo with the tag specified in the env variable LAB_BOX_PYTHON_GUI_TAG
  # If the env variable 'LAB_BOX_PYTHON_GUI_TAG' is empty, check the 'LAB_BOX_PYTHON_GUI_COMMIT' variable
  # When both are empty, the repo is just cloned with depth = 1
  if [ -n "${LAB_BOX_PYTHON_GUI_TAG}" ]    # Check if not empty
  then
    echo "Cloning the Lab-Box Python GUI repo with the tag: ${LAB_BOX_PYTHON_GUI_TAG}"
    git clone --depth 1 --branch $LAB_BOX_PYTHON_GUI_TAG $LAB_BOX_PYTHON_GUI_REPO .
  else
    if [ -n "${LAB_BOX_PYTHON_GUI_COMMIT}" ]    # Check if not empty
    then
      echo "Cloning Lab-Box Python GUI repo and checking out commit: ${LAB_BOX_PYTHON_GUI_COMMIT}"
      git clone $LAB_BOX_PYTHON_GUI_REPO .
      git checkout $LAB_BOX_PYTHON_GUI_COMMIT
    else
      echo "Cloning Lab-Box Python GUI repo with latest commit"
      git clone --depth 1 $LAB_BOX_PYTHON_GUI_REPO .
    fi

    ls .
  fi

  # TODO: install the required python packages from the GUI repo
  # pip3 install -r requirements.txt
  
  # for demonstration purpose we just create a file here
  mkdir /home/"${BASE_USER}"/lab-box
  cd /home/"${BASE_USER}"/lab-box
  touch "test.txt"
fi


#unpack root in the end, so etc file are not overwritten, might need to add two roots int he future
# unpack /filesystem/root /

#####################################################################
### setup services


# update-rc.d change_password defaults
# update-rc.d change_hostname defaults


#cleanup
apt-get clean
apt-get autoremove -y
