#!/usr/bin/env bash
########
set -x
set -e

export LC_ALL=C

source /common.sh

cat /etc/apt/sources.list
ls /etc/apt/sources.list.d
# TODO: how to adapt this and get the latest?
wget -O debian-archive-keyring.deb http://ftp.de.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
apt install ./debian-archive-keyring.deb
cat<<EOF > /etc/apt/sources.list.d/debian.sources
Types: deb deb-src
URIs: https://deb.debian.org/debian
Architectures: armhf
Suites: trixie
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF
cat<<EOF > /etc/apt/preferences.d/debian
Package: *
Pin: origin deb.debian.org
Pin-Priority: 100
EOF
apt-get update
apt-get -y install pyside6-tools




# ADD OUR NEW DEFAULT USER ------------------------------------------------------------------------------------------------------------------------------------
adduser --gecos "" --disabled-password $LAB_BOX_USER
chpasswd <<<"$LAB_BOX_USER:$LAB_BOX_USER_PASSWORD"
usermod -a -G users,adm,dialout,tty,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo $LAB_BOX_USER
# Show a control output which groups the user is in
groups $LAB_BOX_USER

# Make sure user doesn't require a password when running as sudo; https://github.com/Pioreactor/CustoPiZer/blob/pioreactor/workspace/scripts/01-make-pioreactor-user.sh
echo "$LAB_BOX_USER ALL=(ALL) NOPASSWD: ALL" | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/010_$LAB_BOX_USER-nopasswd


# remove "pi" user
deluser --remove-home pi


# Remove SSH pre-authentication banner
if [ -f /etc/ssh/sshd_config.d/rename_user.conf ]
then 
  rm -f /etc/ssh/sshd_config.d/rename_user.conf
fi


# UPDATE SOFTWARE  --------------------------------------------------------------------------------------------------------------------------------------------
apt-get update
apt-get -y full-upgrade
apt-get -y --allow-change-held-packages install python3 python3-pip python3-venv python3-dev git
# apt-get -y --force-yes install --reinstall iputils-ping
# TODO: remove unneeded software?
apt-get autoremove -y


# SETUP RTC ---------------------------------------------------------------------------------------------------------------------------------------------------
# Done like here: https://tutorials-raspberrypi.de/raspberry-pi-rtc-modul-i2c-echtzeituhr/ but there are many tutorials out there
apt-get install -y i2c-tools
echo -e "i2c-dev\nrtc-ds1307" >> /etc/modules
sed -i -e '$i echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device\nhwclock --hctosys\n\n' /etc/rc.local
cat /etc/rc.local


# ADD CONFIG AND OTHER FILES ----------------------------------------------------------------------------------------------------------------------------------
# unpack /filesystem/home /home/"${LAB_BOX_USER}" "${LAB_BOX_USER}"
# unpack /filesystem/home/root /root root
# TODO: make a decision here if image is x32 or x64!
if [[ "$IMAGE_BIT_WIDTH" -eq 32 ]]
then
  unpack /filesystem/boot/x32 /boot/firmware
elif [[ "$IMAGE_BIT_WIDTH" -eq 64 ]]
then
  unpack /filesystem/boot/x64 /boot/firmware
fi


# SETUP RASPI CONFIGF -----------------------------------------------------------------------------------------------------------------------------------------
# raspi-config cli documentation
# https://www.raspberrypi.com/documentation/computers/configuration.html#raspi-config-cli
# systemctl enable ssh
raspi-config nonint do_hostname lab-box
raspi-config nonint do_blanking 1
raspi-config nonint do_net_names 0
raspi-config do_serial_cons 1           # Hardware interfaces like SPI, I2C and Serial are already set in the config.txt file


# MODIFY SPLASHSCREEN WITH OUR LOGO ---------------------------------------------------------------------------------------------------------------------------
mkdir /usr/share/plymouth/themes/lab-box/
unpack /filesystem/usr/share/plymouth/themes/lab-box /usr/share/plymouth/themes/lab-box
plymouth-set-default-theme --rebuild-initrd lab-box
# https://scribles.net/customizing-boot-up-screen-on-raspberry-pi/
# "Replace “console=tty1” with “console=tty3”. This redirects boot messages to tty3."
sed -i 's/console=tty1/console=tty3/g' /boot/cmdline.txt
# First replace a possible new line character at the end of the line, then append our new stuff
sed -i ':a;N;$!ba;s/\n/ /g' /boot/cmdline.txt
echo -n " logo.nologo vt.global_cursor_default=0 loglevel=3" >> /boot/cmdline.txt
cat /boot/cmdline.txt
# This is the ultimate step for Bookworm, otherwise all the above has no effect!
# Thanks to here: https://forums.raspberrypi.com/viewtopic.php?p=2195808#p2195808
update-initramfs -u


# INSTALL AR1100 SETUP TOOL -----------------------------------------------------------------------------------------------------------------------------------
# This clones the rpi-AR1100 fork we have for the Lab-Box. This is a setup tool for the AR1100 touch screen controller on the Lab-Box Raspi Touch Display Module
# Put the raspi-firmware and linux packages on hold (exclude from updated) as it requires /boot/fimrware to be present
apt-get install -y git make g++ libusb-1.0-0-dev libgtk2.0-dev
cd /home/$LAB_BOX_USER
git clone --depth 1 https://github.com/Wardstein/rpi-AR1100.git
cd rpi-AR1100
make
chmod +x AR1100


# INSTALL LAB-BOX PYTHON GUI ----------------------------------------------------------------------------------------------------------------------------------
if [ "${LAB_BOX_PYTHON_GUI_INSTALL}" == "yes" ]
then
  echo "Installing Lab-Box Python GUI from repo ${LAB_BOX_PYTHON_GUI_REPO}"
  mkdir /home/"${LAB_BOX_USER}"/lab-box-python-gui
  pushd /home/"${LAB_BOX_USER}"/lab-box-python-gui

  # Clone the Lab-Box-Python-GUI repo with the tag specified in the env variable LAB_BOX_PYTHON_GUI_TAG
  # If the env variable 'LAB_BOX_PYTHON_GUI_TAG' is empty, check the 'LAB_BOX_PYTHON_GUI_COMMIT' variable
  # When both are empty, the repo is just cloned with depth = 1
  if [ -n "${LAB_BOX_PYTHON_GUI_TAG}" ]    # Check if not empty
  then
    echo "Cloning the Lab-Box Python GUI repo with the tag: ${LAB_BOX_PYTHON_GUI_TAG}"
    git clone --depth 1 --branch $LAB_BOX_PYTHON_GUI_TAG $LAB_BOX_PYTHON_GUI_REPO .
  else
    if [ -n "${LAB_BOX_PYTHON_GUI_COMMIT}" ]    # Check if not empty
    then
      echo "Cloning Lab-Box Python GUI repo and checking out commit: ${LAB_BOX_PYTHON_GUI_COMMIT}"
      git clone $LAB_BOX_PYTHON_GUI_REPO .
      git checkout $LAB_BOX_PYTHON_GUI_COMMIT
    else
      echo "Cloning Lab-Box Python GUI repo with latest commit"
      git clone --depth 1 $LAB_BOX_PYTHON_GUI_REPO .
    fi

    ls .
    if [ -f $LAB_BOX_PYTHON_GUI_STARTFILE ]
    then
      chmod +x $LAB_BOX_PYTHON_GUI_STARTFILE
    fi
  fi

  # Install the required python packages from the GUI repo
  source venv-name
  python -m venv $LAB_BOX_GUI_VENV
  source $LAB_BOX_GUI_VENV/bin/activate
  # TODO: try to get this back up, but currently this does not work, as there is no pyside6 wheel for armhf (32bit)
  # python -m pip install -r requirements.txt
  popd
  
  # cd /home/$LAB_BOX_USER
  # wget http://ftp.de.debian.org/debian/pool/main/p/pyside6/pyside6-tools_6.8.2.1-4_armhf.deb
  # apt install ./pyside6-tools_6.8.2.1-4_armhf.deb
  # apt-get install python3-aiohttp

  # Setup autostart
  AUTOSTART_FILE="/etc/xdg/autostart/lab-box-gui.desktop"
  mkdir -p "$(dirname $AUTOSTART_FILE)"
# NO SPACES BEFORE HERE, THIS BREAKS THE EOF
cat <<'EOF' > $AUTOSTART_FILE
[Desktop Entry]
Type=Application
Name=Lab-Box GUI
Comment=Lab-Box GUI
NoDisplay=false
Exec=/usr/bin/lxterminal -e /home/$LAB_BOX_USER/lab-box-python-gui/$LAB_BOX_PYTHON_GUI_STARTFILE
NotShowIn=GNOME;KDE;XFCE;
EOF
  
  # TODO: do we want to clone the Lab-Box repo with all the modules also? Does it make sense to have a "documentation" also on the Pi?
fi


# Cleanup -----------------------------------------------------------------------------------------------------------------------------------------------------
apt-get clean
apt-get autoremove -y
