#!/usr/bin/env bash
########
set -x
set -e

export LC_ALL=C

source /common.sh


# INSTALL DEPENDENCIES ----------------------------------------------------------------------------------------------------------------------------------------
apt-get install -y python3-numpy nginx


# CHECKOUT WEBSOCKIFY AND SETUP AUTOSTART ---------------------------------------------------------------------------------------------------------------------
cd /home/$RASPI_USER
git clone --depth 1 --branch v0.11.0 https://github.com/novnc/websockify.git
cd websockify
python setup.py install

# websockify should now be installed in /usr/local/bin/
which websockify

# Start websockify at boot in the rc.local file (the sed command inserts the websockify line before the last line, that is what $i does)
# websockify runs in daemon mode, listens on port 5901 and proxies from localhost port 5900 - VNC
sed -i -e '$i websockify -v 5901 127.0.0.1:5900\n\n' /etc/rc.local


# SETUP NGINX -------------------------------------------------------------------------------------------------------------------------------------------------
# Setup nginx to proxy the Lab-Box Display Software and the websockify websocket endpoint
# noVNC (used in the Lab-Box Website) needs a secure connection for the webpage and also the websocket connection must be secure to satisfy modern browsers
# We create a self-signed certificate, backup the nginx default config and overwrite it with our own.
# The config redirects the user to the https version and also proxies the websocket

openssl req -x509 -nodes -days 36500 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj '/CN=lab-box/O=Lab-Box./C=DE'
#chmod +r /etc/ssl/private/nginx-selfsigned.key
#chmod +r /etc/ssl/certs/nginx-selfsigned.crt
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
cat <<EOF > /etc/nginx/sites-enabled/default
# SSL Redirect
server {
	listen 80       default;
	return 301      https://$host$request_uri;
}

server {
	listen                443 ssl default_server;
	listen                [::]:443 ssl default_server;
	server_name           main;
	client_max_body_size  200M;

	ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
	ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

	location / {
		proxy_pass                          http://127.0.0.1:8080;
		proxy_set_header                    Host $host;
		proxy_set_header X-Forwarded-Host   $server_name;
		proxy_set_header X-Real-IP          $remote_addr;
	}

	location /websockify {
		proxy_pass                          http://127.0.0.1:5901;
		proxy_http_version                  1.1;
		proxy_set_header                    Upgrade $http_upgrade;
		proxy_set_header                    Connection "Upgrade";
		proxy_read_timeout                  600s;
		proxy_buffering                     off;
	}
}
EOL


# TODO: NEED TO FIGURE OUT WHICH VNC SERVER WE WANT AND IF WE NEED THE SPECIAL SETUP TO BE COMPATIBLE WITH noVNC


# Cleanup -----------------------------------------------------------------------------------------------------------------------------------------------------
apt-get clean
apt-get autoremove -y
