#!/usr/bin/env bash
########
set -x
set -e

export LC_ALL=C

source /common.sh


# INSTALL DEPENDENCIES ----------------------------------------------------------------------------------------------------------------------------------------
apt-get install -y python3-numpy python3-setuptools nginx


# CHECKOUT WEBSOCKIFY AND SETUP AUTOSTART ---------------------------------------------------------------------------------------------------------------------
# TODO: maybe do this in a venv - also the python packages installes above - as we do not need this anymore after build
cd /home/$RASPI_USER
git clone --depth 1 --branch v0.11.0 https://github.com/novnc/websockify.git
cd websockify
python setup.py install

# websockify should now be installed in /usr/local/bin/
which websockify

# Start websockify at boot as a service, websockify runs in daemon mode, listens on port 5901 and proxies from localhost port 5900 (VNC)
cat << EOF > /etc/systemd/system/websockify.service
[Unit]
Description=Websockify fpr VNC
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/websockify -v 127.0.0.1:5901 127.0.0.1:5900
RestartSec=5
Restart=always

[Install]
WantedBy=multi-user.target
EOF


# With Wayland (Dekstop) now we have "wayvnc" as the VNC server on the Pi. RealVNC does not work anymore.
# As wayvnc has no compatible auth encoding to noVNC (used in the Webinterface of the Lab-Box Python GUI), we need to switch off authentication - for now.
# (enable_pam is authentication with the linux OS user credentials, we do not want that, and enable_auth disables authentication at all)
# Append a user and password anyways, with a comment for the future when authentication in noVNC should work
sed -i -e "s/enable_pam=.*/enable_pam=false/g" /etc/wayvnc/config
sed -i -e "s/enable_auth=.*/enable_auth=false/g" /etc/wayvnc/config
cat << EOF >> /etc/wayvnc/config
# Username and password are only here for future use, when noVNC and wayvnc share a common authentication scheme...
username=lab-box-vnc
password=lab-box-vnc
EOF


# SETUP NGINX -------------------------------------------------------------------------------------------------------------------------------------------------
# Setup nginx to proxy the Lab-Box Display Software and the websockify websocket endpoint
# noVNC (used in the Lab-Box Website) needs a secure connection for the webpage and also the websocket connection must be secure to satisfy modern browsers
# We create a self-signed certificate, backup the nginx default config and overwrite it with our own.
# The config redirects the user to the https version and also proxies the websocket

openssl req -x509 -nodes -days 36500 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj '/CN=lab-box/O=Lab-Box./C=DE'
#chmod +r /etc/ssl/private/nginx-selfsigned.key
#chmod +r /etc/ssl/certs/nginx-selfsigned.crt
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
cat <<EOF > /etc/nginx/sites-enabled/default
# SSL Redirect
server {
	listen 80       default;
	return 301      https://$host$request_uri;
}

server {
	listen                443 ssl default_server;
	listen                [::]:443 ssl default_server;
	server_name           main;
	client_max_body_size  200M;

	ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
	ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

	location / {
		proxy_pass                          http://127.0.0.1:8080;
		proxy_set_header                    Host $host;
		proxy_set_header X-Forwarded-Host   $server_name;
		proxy_set_header X-Real-IP          $remote_addr;
	}

	location /websockify {
		proxy_pass                          http://127.0.0.1:5901;
		proxy_http_version                  1.1;
		proxy_set_header                    Upgrade $http_upgrade;
		proxy_set_header                    Connection "Upgrade";
		proxy_read_timeout                  600s;
		proxy_buffering                     off;
	}
}
EOL


# Cleanup -----------------------------------------------------------------------------------------------------------------------------------------------------
apt-get clean
apt-get autoremove -y
