name: Build Image

on: 
  workflow_dispatch:
    inputs:
      # MAXIMUM 10 PARAMETERS POSSIBLE
      labbox-python-software-tag:
        description: "Lab-Box Python Software Tag"
        required: false
        default: ''
      release-name:
        description: "Release Name"
        required: true
        default: ''
      default-user:
        description: "Raspberry Pi User"
        required: true
        default: 'lab-box'
      default-user-password:
        description: "Raspberry Pi Password"
        required: true
        default: 'lab-box-pi'
      # TODO: add a parameter if image is x32 or x64!


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils zip qemu-user-static python3-git
    
    
    - name: "Setup Environment"
      run: |
        # Image bit width, 32/64bit ... 32bit could be possible with apt packages instead of pip wheels? (CURRENTLY ONLY 64bit WORKS, as the pre-build PySide6 package is only available for ARM64)
        IMAGE_BIT_WIDTH=32
        echo "IMAGE_BIT_WIDTH=$IMAGE_BIT_WIDTH" >> $GITHUB_ENV
        # Build image name (to rename and zip)
        IMAGE_NAME="$(date +'%Y-%m-%d')_Lab-Box_RaspiTouchDisplayModule_Image-${{ inputs.release-name }}.img"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        IMAGE_NAME_TAR_XZ="$IMAGE_NAME.tar.xz"
        echo "IMAGE_NAME_TAR_XZ=$IMAGE_NAME_TAR_XZ" >> $GITHUB_ENV

        LAB_BOX_PYTHON_GUI_TAG=${{ inputs.labbox-python-software-tag }}
        echo "LAB_BOX_PYTHON_GUI_TAG=$LAB_BOX_PYTHON_GUI_TAG" >> $GITHUB_ENV
        LAB_BOX_USER=${{ inputs.default-user }}
        echo "LAB_BOX_USER=$LAB_BOX_USER" >> $GITHUB_ENV
        LAB_BOX_USER_PASSWORD=${{ inputs.default-user-password }}
        echo "LAB_BOX_USER_PASSWORD=$LAB_BOX_USER_PASSWORD" >> $GITHUB_ENV


    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS


    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        path: repository
        submodules: true


    - name: Download Raspbian Image
      run: |
        # TODO: maybe got the OS info with the script from the SmartAmp image. Always choosing the latest might be error prone
        if [[ "$IMAGE_BIT_WIDTH" -eq 32 ]]
        then
          cd repository/src/image
          # wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf_latest'    # LITE IS WITHOUT DESKTOP!
          wget -c --trust-server-names 'downloads.raspberrypi.com/raspios_armhf_latest'
        elif [[ "$IMAGE_BIT_WIDTH" -eq 64 ]]
        then
          # cd repository/src/image-raspios_lite_arm64
          cd repository/src/image-raspberrypiarm64
          # wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_arm64_latest'    # LITE IS WITHOUT DESKTOP!
          wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_arm64_latest'
        else
          echo "Env variable IMAGE_BIT_WIDTH value: $IMAGE_BIT_WIDTH not valid!"
          exit 1
        fi
        # Store the image name for later
        ORG_IMAGE_NAME=$(ls *.img.xz)
        echo $ORG_IMAGE_NAME
        echo "ORG_IMAGE_NAME=$ORG_IMAGE_NAME" >> $GITHUB_ENV


    - name: Update CustomPiOS Paths
      run: |
        cd repository/src
        ../../CustomPiOS/src/update-custompios-paths
    

    - name: Build Image
      run: |
        sudo modprobe loop
        cd repository/src
        if [[ "$IMAGE_BIT_WIDTH" -eq 32 ]]
        then
          sudo bash -x ./build_dist
        elif [[ "$IMAGE_BIT_WIDTH" -eq 64 ]]
        then
          sudo bash -x ./build_dist rpios_lite_arm64
        else
          echo "Env variable IMAGE_BIT_WIDTH value: $IMAGE_BIT_WIDTH not valid!"
          exit 1
        fi

    - name: "Prepare release"
      run: |        
        mkdir build
        cd build

        # Rename and move the image (../ because we are in the build directory now!)
        ls ../repository/src/workspace
        cp ../repository/src/workspace/*.img ${{ env.IMAGE_NAME }}
        tar -cJf ${{ env.IMAGE_NAME_TAR_XZ }} ${{ env.IMAGE_NAME }}

        # md5sum ${{ env.IMAGE_NAME_TAR_XZ }} > ${{ env.IMAGE_NAME_TAR_XZ }}.md5
        IMAGE_ARCHIVE_MD5SUM=`md5sum ${{ env.IMAGE_NAME_TAR_XZ }}` && export IMAGE_ARCHIVE_MD5SUM
        echo "IMAGE_ARCHIVE_MD5SUM=$IMAGE_ARCHIVE_MD5SUM" >> $GITHUB_ENV
        
        # sha512sum ${{ env.IMAGE_NAME_TAR_XZ }} > ${{ env.IMAGE_NAME_TAR_XZ }}.sha512
        IMAGE_ARCHIVE_SHA512SUM=`sha512sum ${{ env.IMAGE_NAME_TAR_XZ }}` && export IMAGE_ARCHIVE_SHA512SUM
        echo "IMAGE_ARCHIVE_SHA512SUM=$IMAGE_ARCHIVE_SHA512SUM" >> $GITHUB_ENV
        
        ls -la
        mkdir dist
        cp ${{ env.IMAGE_NAME_TAR_XZ }} dist/
        cat $IMAGE_ARCHIVE_MD5SUM > dist/${{ env.IMAGE_NAME_TAR_XZ }}.md5
        cat $IMAGE_ARCHIVE_SHA512SUM > dist/${{ env.IMAGE_NAME_TAR_XZ }}.sha512


        # TODO: add same cool original image infos in this text as from the SmartAmp Image
        cat <<'EOF' > release.md
        Image for the [Lab-Box](https://github.com/Wardstein/Lab-Box) [RaspberryPi Touch Display Module](https://github.com/Wardstein/Lab-Box/Modules/Display)
        To use this image, copy it to an SD card with at least 8GB. You can use e.g. [Balena Etcher](https://etcher.balena.io/).

        DOWNLOAD HERE: [${{ vars.FILE_DOWNLOAD_BASE_URL}}/${{ vars.FTP_UPLOAD_SUBFOLDER }}/${{ env.IMAGE_NAME_TAR_XZ }}](${{ env.IMAGE_NAME_TAR_XZ }})
        MD5: ${{ env.IMAGE_ARCHIVE_MD5SUM}}
        SHA512: ${{ env.IMAGE_ARCHIVE_SHA512SUM}}

        Default credentials:
        * User: "${{ env.LAB_BOX_USER }}"
        * Password: "${{ env.LAB_BOX_USER_PASSWORD }}"

        Pre-installed Lab-Box Python GUI version: "${{ env.LAB_BOX_PYTHON_GUI_TAG }}" (when empty it was the latest while creation)

        Based on the RaspberryPi image: ${{ env.ORG_IMAGE_NAME }}

        Created with [CustomPiOS](https://github.com/guysoft/CustomPiOS)

        <!-- mark:untested -->
        EOF

        # Copy the release info also for upload with unique name from image
        cp release.md dist/RELEASE_${{ env.IMAGE_NAME }}.md
        ls -la dist

    - name: "Upload image to FTP server"
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "build/dist"
        remoteDir: ${{ vars.FTP_UPLOAD_SUBFOLDER }}
    
    # https://github.com/softprops/action-gh-release
    # Needs "Workflow permissions" in Repo->Settings->Actions->Genernal set to "Read and write permissions"
    - name: "Create release & attach assets"
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ inputs.release-name }}
        tag_name: ${{ inputs.release-name }}
        body_path: "build/release.md"
        prerelease: false
        fail_on_unmatched_files: true
        # files: |
        #   build/${{ env.IMAGE_NAME_TAR_XZ }}
        #   build/${{ env.IMAGE_NAME_TAR_XZ }}.md5
        #   build/${{ env.IMAGE_NAME_TAR_XZ }}.sha512
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

