name: Release was deleted

on:
  release:
    # Possible types: published, unpublished, created, edited, deleted, prereleased, released
    #types: [deleted]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      run: |
        echo "Tag name from env.GITHUB_REF: ${{ env.GITHUB_REF }}"
        echo "Tag name from env.GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}"
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{ github.ref_name }}"
        
        FTP_UPLOAD_FOLDER="${{ vars.FTP_UPLOAD_IMAGE_SUBFOLDER }}/${{ github.ref_name }}"
        echo "FTP_UPLOAD_FOLDER=$FTP_UPLOAD_FOLDER" >> $GITHUB_ENV
        
        echo "FTP_UPLOAD_FOLDER: $FTP_UPLOAD_FOLDER"
